#!/usr/bin/env python3
"""
JAKALA GTM OS — Automated Weekly Lead Radar
Runs every Monday morning via GitHub Actions.
Generates intelligence/daily-leads/YYYY-MM-DD.md by analysing
all account data and surfacing actionable signals with Claude.

Usage:
  python3 scripts/lead_radar.py              # Generate and save
  python3 scripts/lead_radar.py --dry-run    # Print to stdout only
  python3 scripts/lead_radar.py --date 2026-03-17  # Override date
"""

import os
import re
import sys
import argparse
from pathlib import Path
from datetime import date

import anthropic

BASE_DIR     = Path(__file__).parent.parent
ACCOUNTS_DIR = BASE_DIR / "Accounts"
INTEL_DIR    = BASE_DIR / "intelligence"
OUTPUT_DIR   = INTEL_DIR / "daily-leads"


def read(rel):
    p = BASE_DIR / rel
    return p.read_text(encoding="utf-8") if p.exists() else ""


def load_pipeline_context():
    """Gather lean account summaries for all ICP 6+ accounts."""
    lines = []
    for folder in sorted(ACCOUNTS_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith("."):
            continue
        ov_path = folder / "overview.md"
        st_path = folder / "strategy.md"
        sk_path = folder / "stakeholders.md"
        na_path = folder / "next-actions.md"

        ov = ov_path.read_text(encoding="utf-8") if ov_path.exists() else ""
        icp_m  = re.search(r"ICP Score[:\s]+(\d+)/10", ov, re.I)
        deal_m = re.search(r"Deal Score[:\s]+(\d+)/10", ov, re.I)
        icp  = int(icp_m.group(1))  if icp_m  else 0
        deal = int(deal_m.group(1)) if deal_m else 0

        if icp < 6 and deal < 6:
            continue

        buyer = "TBD"
        if sk_path.exists():
            sk = sk_path.read_text(encoding="utf-8")
            bm = re.search(r"###\s+(.+)", sk)
            tm = re.search(r"\*\*Title:\*\*\s*(.+)", sk)
            if bm:
                buyer = bm.group(1).strip()
                if tm:
                    buyer += f" ({tm.group(1).strip()})"

        st = st_path.read_text(encoding="utf-8") if st_path.exists() else ""
        gtm_m = re.search(r"GTM Strategy[:\s*#]+(.+)", st, re.I)
        gtm = gtm_m.group(1).strip()[:60] if gtm_m else "—"

        na = na_path.read_text(encoding="utf-8")[:300] if na_path.exists() else ""

        lines.append(
            f"### {folder.name.replace('-',' ').title()} | ICP {icp} | Deal {deal}\n"
            f"GTM: {gtm} | Buyer: {buyer}\n"
            + (f"Actions: {na[:200]}\n" if na else "")
        )
    return "\n".join(lines[:50])


def get_last_radar():
    files = sorted(OUTPUT_DIR.glob("*.md"), reverse=True)
    if files:
        return files[0].read_text(encoding="utf-8")[:1500]
    return ""


def generate_radar(today_str: str, dry_run: bool):
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    pipeline   = load_pipeline_context()
    last_radar = get_last_radar()
    top_opps   = read("intelligence/top-opportunities.md")[:1500]

    prompt = f"""You are a senior Nordic market intelligence analyst for JAKALA.
TODAY: {today_str}
SCOPE: Norway (NO), Sweden (SE), Denmark (DK) ONLY. Exclude UK, France, all other markets.

FULL PIPELINE CONTEXT:
{pipeline}

PREVIOUS RADAR (skip identical signals unless urgency changed):
{last_radar[:800]}

TOP OPPORTUNITIES:
{top_opps}

Generate today's Lead Radar as a markdown file with EXACTLY this structure:

# Daily Lead Radar — {today_str}

**Week XX — [Day]**
**Scope: Norway · Sweden · Denmark only**
**Generated by:** Automated weekly run

---

## Signal Summary
[2-3 sentences: accounts monitored, new signals, most urgent action today]

---

## 🔴 URGENT — Act This Week
[2-3 signals. Format each as:
### [Company] ([Country]) — [Signal type]
**Signal:** [What happened]
**Why it matters:** [Commercial reason]
**GTM:** [Strategy] | **Entry:** [Offer + price range]
**Buyer:** [Name or TBD] | **Deal est.:** [€ value]
**Action:** [Specific next step] | **Window:** [Time remaining]]

---

## 🟡 HIGH — Act This Month
[3-4 signals, same format]

---

## 📋 Buyer Gaps — Unlock These
| Account | Country | Gap | How to find | Forecast unlock |
[Only ICP 7+ accounts with TBD buyer]

---

## Pattern Signals — Watch List
| Account | Country | Signal | Watch for |
[Early-stage signals not yet actionable]

---

## Weekly Scorecard
| Metric | Value |
| Accounts monitored | X |
| New signals | X |
| URGENT | X |
| HIGH | X |
| Outreach sent | 0 |
| Meetings booked | 0 |

---

## Today's 3 Actions (in order)
1. [Most time-critical — name the person]
2. [Second priority]
3. [Third priority]

---

Rules:
- Only use signals from the pipeline context — do NOT fabricate events
- Focus on: new executives, leadership vacancies, AI announcements, platform migrations
- Named buyers = higher priority
- Keep under 900 words total
- Return ONLY the markdown"""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=3000,
        messages=[{"role": "user", "content": prompt}],
    )

    content = response.content[0].text.strip()

    if dry_run:
        print(content)
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_file = OUTPUT_DIR / f"{today_str}.md"

    if output_file.exists():
        print(f"  ℹ  File already exists for {today_str} — overwriting.")

    output_file.write_text(content, encoding="utf-8")
    print(f"  ✓  Lead radar written: {output_file}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout, do not write file")
    parser.add_argument("--date",    type=str, default=date.today().isoformat(), help="Override date (YYYY-MM-DD)")
    args = parser.parse_args()

    print(f"\n  JAKALA GTM OS — Lead Radar")
    print(f"  Date: {args.date}")
    print(f"  Mode: {'DRY RUN' if args.dry_run else 'LIVE'}\n")

    generate_radar(args.date, args.dry_run)
    print()


if __name__ == "__main__":
    main()
